In [1]:
from google.colab import files
uploaded = files.upload()

Saving olist_order_reviews_dataset.csv to olist_order_reviews_dataset.csv
Saving olist_orders_dataset.csv to olist_orders_dataset.csv
Saving olist_products_dataset.csv to olist_products_dataset.csv
Saving olist_sellers_dataset.csv to olist_sellers_dataset.csv
Saving product_category_name_translation.csv to product_category_name_translation.csv
Saving olist_customers_dataset.csv to olist_customers_dataset.csv
Saving olist_geolocation_dataset.csv to olist_geolocation_dataset.csv
Saving olist_order_items_dataset.csv to olist_order_items_dataset.csv
Saving olist_order_payments_dataset.csv to olist_order_payments_dataset.csv

In [2]:
import pandas as pd

orders = pd.read_csv("/content/olist_customers_dataset.csv")
orders = pd.read_csv("/content/olist_geolocation_dataset.csv")
orders = pd.read_csv("/content/olist_order_items_dataset.csv")
orders = pd.read_csv("/content/olist_order_payments_dataset.csv")
orders = pd.read_csv("/content/olist_order_reviews_dataset.csv")
orders = pd.read_csv("/content/olist_orders_dataset.csv")
orders = pd.read_csv("/content/olist_products_dataset.csv")
orders = pd.read_csv("/content/olist_sellers_dataset.csv")
orders = pd.read_csv("/content/product_category_name_translation.csv")
orders.head(5)

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [3]:
import pandas as pd

customers = pd.read_csv("/content/olist_customers_dataset.csv")
geolocation = pd.read_csv("/content/olist_geolocation_dataset.csv")
order_items = pd.read_csv("/content/olist_order_items_dataset.csv")
payments = pd.read_csv("/content/olist_order_payments_dataset.csv")
reviews = pd.read_csv("/content/olist_order_reviews_dataset.csv")
orders = pd.read_csv("/content/olist_orders_dataset.csv")
products = pd.read_csv("/content/olist_products_dataset.csv")
sellers = pd.read_csv("/content/olist_sellers_dataset.csv")
category_translation = pd.read_csv("/content/product_category_name_translation.csv")

In [4]:
print("Customers:", customers.shape)
print("Orders:", orders.shape)
print("Order Items:", order_items.shape)
print("Payments:", payments.shape)
print("Products:", products.shape)
print("Sellers:", sellers.shape)
print("Reviews:", reviews.shape)

Customers: (99441, 5)
Orders: (99441, 8)
Order Items: (112650, 7)
Payments: (103886, 5)
Products: (32951, 9)
Sellers: (3095, 4)
Reviews: (99224, 7)

In [5]:
orders['order_id'].nunique()
order_items['order_id'].nunique()

98666

In [6]:
order_items.shape
orders.shape

(99441, 8)

In [7]:
missing_orders = order_items[~order_items['order_id'].isin(orders['order_id'])]
len(missing_orders)

0

In [8]:
orders_without_items = orders[~orders['order_id'].isin(order_items['order_id'])]
len(orders_without_items)

775

In [9]:
len(orders_without_items)

775

In [10]:
orders_without_items['order_status'].value_counts()

order_status
unavailable    603
canceled       164
created          5
invoiced         2
shipped          1
Name: count, dtype: int64

In [11]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP